### ISSUE TITLE
Video/Broadcasting Overlap

### ISSUE THREAD

**Issue by peternewman** [stingalleman/awesome-audiovisual#13]
Hi,

Just in case you're not aware, the European Broadcasting Union (EBU) also has a pre-existing awesome list of broadcasting stuff here:
https://github.com/ebu/awesome-broadcasting#readme

There seems to be quite a bit of overlap with some of the sections (e.g. video and the IP section) and I don't know what you think about merging them, or at the very least signposting heavily to the equivalent broadcasting sections.

**Comment by stingalleman** [comment]
Didn't even know this existed.. I'll probably delete the broadcast categories and link that list instead. Going to do it later today.


Thank you!
